### ISSUE TITLE
Error on The First Step of the Process

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [martani/Twitter-Archive-Eraser#3]
Hey there,

Whenever I hit "Sign in" button, it spits out this error:

=====

Please make sure that:
- your date/time is accurate
- you entered the exact Twitter PIN

Twitter error message: An error occurred while sending request.

=====

How do I solve that?
My time is correct. And I didn't yet get the browser sign in page to get the PIN from to enter it.

Technicals:
Windows 8.1
Using Avira Free AV
Using ZoneAlarm Firewall (also tried after disabling it)
Used both, Standalone package and the setup package. Both got me different errors.

====

The setup package didn't install at all, saying it needs assembly Microsoft.Web.Infrastructure version 1.0.0.0 be installed in the Global Assembly Cache.

====

I have no idea what that even means.

Any help is much appreciated.

**Comment by martani** [comment]
Did you try running the app as administrator? This is mentioned in the FAQ page (http://martani.github.io/Twitter-Archive-Eraser/faq.html) and solved this issue for other users

**Comment by BoringUserWhoCantCode** [comment]
@martani Sorry I forgot to mention that. I tried. Same error.

**Comment by martani** [comment]
Looks like you have some software preventing the app to open twitter login page in the browser according to the error message...

**Comment by BoringUserWhoCantCode** [comment]
Do you of anyway I can work around that?

Will running it in the clean Windows VM help bypass the Host problem? Just an idea.. I'll try anyway :)

**Comment by martani** [comment]
I guess that should work. Also, relaxing AV/firewall restrictions on the app could do it also!

**Comment by BoringUserWhoCantCode** [comment]
All good! Just setup a VM with clean Windows install and working through the process now.

Hope it goes well with no error.

Starting a clean slate with same followers. I'd like to deeply thank you, @martani. Like truly thanks!
